services:
  rami-server:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: rami-server
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - "8000:8000"
    volumes:
      - ./data:/app/data:ro
      - ./logs:/app/logs
    networks:
      - platform-stack_backend

networks:
  platform-stack_backend:
    external: true
    name: platform-stack_backend